version: '3'

services:

  ws:
    container_name: people-api
    image: openjdk:11.0.9.1-oraclelinux8
    volumes:
      - .:/usr/src
    ports:
      - "8080:8080"
    working_dir: /usr/src
    command: >
      sh -c "./gradlew bootRun"
    networks:
      - ws

volumes:
  data:
    driver: local

networks:
  ws:
    driver: bridge
